//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by chirrup.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CHIRRUP_DIALOG              102
#define IDS_VERSION                     102
#define IDS_ABOUT_SUPPORT               103
#define IDS_ABOUT_SUPPORT2              104
#define IDS_ABOUT_COMMUNITY             105
#define IDS_ABOUT_COMMUNITY2            106
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CONFIG               129
#define IDB_DEFAULT_IMAGE               130
#define IDB_TWITTER                     131
#define IDB_DELICIOUS                   132
#define IDB_HATENABOOKMARK              133
#define IDB_HATENAGROUP                 134
#define IDB_GOOGLEGROUPS                135
#define IDD_PROCEEDING_DIALOG           136
#define IDB_TWITTERWIKI                 137
#define IDB_TWITTER_CHIRRUP             138
#define IDB_MIXI                        139
#define IDB_DIGG                        140
#define IDB_MAGNOLIA                    141
#define IDB_LIVEDOORCLIP                142
#define IDB_YAHOO                       143
#define IDB_BLOGLINES                   144
#define IDB_GOOGLE                      145
#define IDB_LIVEDOOR                    146
#define IDB_DEFAULT_IMAGE_NORMAL        147
#define IDC_HAND2                       148
#define IDD_PROFILE_DIALOG              149
#define IDB_TWITTER_SEARCH              150
#define IDB_BALLOON                     151
#define IDD_DIRECTMESSAGE_DIALOG        152
#define IDD_DIRECTMESSAGE_LIST_DIALOG   153
#define IDB_CAT                         154
#define IDB_JAIKU                       157
#define IDD_SETTING_DIALOG              158
#define IDD_TAB_TWITTER                 159
#define IDB_WASSR                       161
#define IDB_MOGO2                       162
#define IDB_TIMELOG                     163
#define IDB_HARUFM                      165
#define IDB_HATENASTAR                  166
#define IDD_TUMBLR_DIALOG               167
#define IDB_TUMBLR                      169
#define IDB_FAVOTTER                    170
#define IDD_UPLOAD_IMAGE_DIALOG         171
#define IDB_BITMAP_THUMBNAIL            172
#define IDB_FLICKR                      173
#define IDD_DIALOG_PROXY_INFO           174
#define IDB_GYAZO                       174
#define IDD_TAB_JAIKU                   175
#define IDB_HATENAFOTOLIFE              175
#define IDD_TAB_WASSR                   176
#define IDB_TWITTERSNS                  176
#define IDD_TAB_MOGO2                   177
#define IDD_TAB_TIMELOG                 178
#define IDD_TAB_HARUFM                  179
#define IDB_LOGO_TWITTER                179
#define IDD_TAB_HATENA                  180
#define IDI_TASKTRAY_ICON               180
#define IDD_TAB_TUMBLR                  181
#define IDD_TAB_PROXY                   182
#define IDD_TAB_GYAZO                   183
#define IDD_TAB_FLICKR                  184
#define IDD_SETTING_UPLOAD_WASSR        185
#define IDD_CHANNEL_WASSR               186
#define IDD_TAB_HATENAHAIKU             187
#define IDB_HATENAHAIKU                 187
#define IDD_TWITTER_AUTH_DIALOG         188
#define IDD_JAIKU_AUTH_DIALOG           189
#define IDD_BLOGID_DIALOG               190
#define IDD_INPUT_PIN                   192
#define IDC_MONOLOGUE                   1001
#define IDC_POST_MONOLOGUE              1002
#define IDC_EDIT_USERNAME               1003
#define IDC_EDIT_PASSWORD               1004
#define IDC_UPDATE                      1005
#define IDC_EDIT_LOGFILENAME            1005
#define IDC_PERIOD                      1006
#define IDC_EDIT_LOGFILENAME2           1006
#define IDC_FRIEND001                   1007
#define IDC_FRIEND002                   1008
#define IDC_FRIEND003                   1009
#define IDC_FRIEND004                   1010
#define IDC_FRIEND005                   1011
#define IDC_FRIEND006                   1012
#define IDC_FRIEND007                   1013
#define IDC_LIST_BLOGID                 1013
#define IDC_FRIEND008                   1014
#define IDC_EDIT_BLOGNAME               1014
#define IDC_FRIEND009                   1015
#define IDC_FRIEND010                   1016
#define IDC_FRIEND011                   1017
#define IDC_FRIEND012                   1018
#define IDC_FRIEND013                   1019
#define IDC_FRIEND014                   1020
#define IDC_FRIEND015                   1021
#define IDC_FRIEND016                   1022
#define IDC_FRIEND017                   1023
#define IDC_FRIEND018                   1024
#define IDC_FRIEND019                   1025
#define IDC_FRIEND020                   1026
#define IDC_TWITTER                     1027
#define IDC_HATENAGROUP                 1028
#define IDC_STATIC_PROCEED_STRING       1029
#define IDC_HATENABOOKMARK              1029
#define IDC_DELICOUS                    1030
#define IDC_DELICIOUS                   1030
#define IDC_GOOGLEGROUPS                1031
#define IDC_TWITTERWIKI                 1032
#define IDC_TWITTER_CHIRRUP             1034
#define IDC_MIXI                        1035
#define IDC_DIGG                        1036
#define IDC_MAGNOLIA                    1037
#define IDC_LIVEDOORCLIP                1038
#define IDC_LIVEDOOR                    1039
#define IDC_BLOGLINES                   1040
#define IDC_GOOGLE                      1041
#define IDC_PROFILE_ICON                1041
#define IDC_YAHOO                       1042
#define IDC_RECV_DIRECTMESSAGE          1043
#define IDC_SETTING_ACCOUNT             1044
#define IDC_DESCRIPTION                 1045
#define IDC_START_CAPTURE               1045
#define IDC_NAME                        1046
#define IDC_SCREENNAME                  1047
#define IDC_TWITTER_SEARCH              1047
#define IDC_LOCATION                    1048
#define IDC_FRIEND_URL                  1049
#define IDC_EDIT_LAST_STATUS            1050
#define IDC_CHECK_BROWSING              1051
#define IDC_EDIT_DIRECTMESSAGE          1052
#define IDC_CHECK_MULTIPOST             1052
#define IDC_EDIT_SENDER                 1054
#define IDC_EDIT_PROXY_SERVER_NAME      1055
#define IDC_EDIT_TEXT                   1055
#define IDC_EDIT_PROXY_PORT_NUMBER      1056
#define IDC_EDIT_DATETIME               1056
#define IDC_EDIT_PROXY_USER_NAME        1057
#define IDC_BUTTON_PREV                 1057
#define IDC_EDIT_PROXY_PASSWORD         1058
#define IDC_BUTTON_NEXT                 1058
#define IDC_RICHEDIT_MESSAGES           1058
#define IDC_BUTTON_REPLY                1059
#define IDC_COMBO_TIMELINE_TYPE         1060
#define IDC_BUTTON_DELETE               1060
#define IDC_EDIT_RECIPIENT              1061
#define IDC_CAT                         1062
#define IDC_WEB_URL                     1063
#define IDC_MAIL_ADDR                   1064
#define IDC_MANAGE_FRIEND               1064
#define IDC_JAIKU                       1065
#define IDC_EXECUTING                   1066
#define IDC_BUTTON_FILESPEC             1068
#define IDC_BUTTON_FILESPEC2            1069
#define IDC_BUTTON_SETTING_UPLOAD       1070
#define IDC_TAB_SETTING                 1071
#define IDC_BUTTON_ACCEPT               1072
#define IDC_EDIT_LOGFILENAME3           1073
#define IDC_BUTTON_FILESPEC3            1074
#define IDC_CHECK_FRIENDS_TIMELINE      1075
#define IDC_CHECK_PUBLIC_TIMELINE       1076
#define IDC_VERSION                     1076
#define IDC_CHECK_USER_TIMELINE         1077
#define IDC_MOGO2                       1077
#define IDC_CHECK_FRIENDS_TIMELINE2     1078
#define IDC_WASSR                       1078
#define IDC_CHECK_PUBLIC_TIMELINE2      1079
#define IDC_TIMELOG                     1079
#define IDC_CHECK_USER_TIMELINE2        1080
#define IDC_HARUFM                      1080
#define IDC_CHECK_REPLIES               1081
#define IDC_HATENASTAR                  1081
#define IDC_CHECK_CHANNEL               1081
#define IDC_EDIT_LOGFILENAME4           1082
#define IDC_USE_TWITSTAR                1082
#define IDC_CHECK_REPLIES2              1083
#define IDC_URL_JAIKU_APIKEY            1083
#define IDC_BUTTON_FILESPEC4            1084
#define IDC_USE_TUMBLR                  1084
#define IDC_EDIT_QUOTE                  1085
#define IDC_EDIT_URL                    1086
#define IDC_EDIT_TITLE                  1087
#define IDC_USE_PROXY                   1087
#define IDC_FAVOTTER                    1088
#define IDC_EDIT_COMMENT                1088
#define IDC_TUMBLR                      1089
#define IDC_IMAGE_FILENAME              1090
#define IDC_CAPTION                     1091
#define IDC_APPLIED                     1091
#define IDC_TARGET_NAME                 1092
#define IDC_BITMAP_THUMBNAIL            1093
#define IDC_WRITE_LOGFILE               1094
#define IDC_STATIC_QUESTION             1095
#define IDC_GYAZO                       1097
#define IDC_FLICKR                      1098
#define IDC_HATENAFOTOLIFE              1099
#define IDC_TWITTERSNS                  1100
#define IDC_LOGO_TWITTER                1101
#define IDC_EDIT_LOGFILENAME_UPLOAD     1102
#define IDC_LIST                        1107
#define IDC_URL_HATENAHAIKU_SETTING     1108
#define IDC_HATENAHAIKU                 1109
#define IDC_RADIO_OAUTH                 1110
#define IDC_RADIO_BASIC                 1111
#define IDC_BUTTON_GET_TOKEN            1112
#define IDC_TOKEN_STATUS                1113
#define IDC_BUTTON_SET_AUTH             1114
#define IDC_CURRENT_AUTH                1115
#define IDC_OPENSSL                     1160
#define IDC_ICONV                       1161
#define IDC_LIBPNG                      1162
#define IDC_BUTTON_SELECT_TARGET        1162
#define IDC_ZLIB                        1163
#define IDC_EDIT_PIN                    1163
#define IDS_MAIL_ADDR                   61230
#define IDS_WEB_URL                     61231
#define IDS_CHIRRUP_SUPPORT             61232
#define IDS_CHIRRUP_COMMUNITY           61233
#define IDS_CHIRRUP_COMMUNITY2          61234
#define IDS_TWITTER_OA001               61235
#define IDS_TWITTER_OA002               61236
#define IDS_JAIKU_OA001                 61237
#define IDS_JAIKU_OA002                 61238
#define IDS_TXT_CONTINUE_PROCEEDING     61565
#define IDS_URL_TWITTER                 61566
#define IDS_URL_TWITTERWIKI             61567
#define IDS_URL_HATENAGROUP             61568
#define IDS_URL_HATENABOOKMARK          61569
#define IDS_URL_DELICIOUS               61570
#define IDS_URL_GOOGLEGROUPS            61571
#define IDS_URL_TWITTER_CHIRRUP         61572
#define IDS_URL_MIXI                    61573
#define IDS_URL_DIGG                    61574
#define IDS_URL_MAGNOLIA                61575
#define IDS_URL_LIVEDOORCLIP            61576
#define IDS_URL_GOOGLE                  61577
#define IDS_URL_BLOGLINES               61578
#define IDS_URL_YAHOO                   61579
#define IDS_URL_LIVEDOOR                61580
#define IDS_URL_TWITTER_SEARCH          61581
#define IDS_URL_JAIKU                   61582
#define IDS_URL_MOGO2                   61583
#define IDS_URL_WASSR                   61584
#define IDS_URL_TIMELOG                 61585
#define IDS_URL_HARUFM                  61586
#define IDS_URL_HATENASTAR              61587
#define IDS_URL_JAIKU_APIKEY            61588
#define IDS_URL_MOGO2STAR               61589
#define IDS_URL_FAVOTTER                61590
#define IDS_URL_TUMBLR                  61591
#define IDS_SIG_HEAD                    61592
#define IDS_SIG_TAIL                    61593
#define IDS_URL_HATENAFOTOLIFE          61594
#define IDS_URL_FLICKR                  61595
#define IDS_URL_GYAZO                   61596
#define IDS_URL_TWITTERSNS              61597
#define IDS_URL_HATENAHAIKU_SETTING     61598
#define IDS_URL_HATENAHAIKU             61599
#define IDS_URL_TWITTER_REQUEST_TOKEN   61600
#define IDS_URL_TWITTER_ACCESS_TOKEN    61601
#define IDS_URL_TWITTER_AUTHORIZE       61602
#define IDS_ACCESSTOKEN_ACQUIRED        61603
#define IDS_ACCESSTOKEN_UNTAKEN         61604
#define IDS_URL_JAIKU_REQUEST_TOKEN     61605
#define IDS_URL_JAIKU_ACCESS_TOKEN      61606
#define IDS_URL_JAIKU_AUTHORIZE         61607
#define IDS_DEFAULT_TARGET              61608
#define IDS_TXT_INPUT_PIN               61609
#define IDS_TTL_INPUT_PIN               61610

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
